### ISSUE TITLE
Confirm that everyone has successfully cloned and can push a new branch

### ISSUE THREAD

**Issue by AnnaCate** [jrscodeschool-5-2019/group-project-spring-2019#1]
once you have accomplished this task, leave comment confirming so.
Anna is done.
Done! - Austin
It worked -Kevin
Done - Michael
Done - Joe

**Comment by moquinad** [comment]
AAAAAHHHHHH!!!!

**Comment by AnnaCate** [comment]
@MichaelGreco7 we can't see your branch. Make sure to do `git checkout -b michael-test-branch` and then `git push origin michael-test-branch`. Comment here when you've done this.

**Comment by kevinleemoody** [comment]
Ok I can commit and comment.

**Comment by MichaelGreco7** [comment]
Ok sorry I got it

**Comment by AnnaCate** [comment]
@MichaelGreco7 I see that you edited the README file on the master branch. We're trying to avoid doing any edits directly to the master branch, since this is a collaborative project. So what you'll need to do is create a new branch, named `michael-test` or something like that. You don't need to edit any files. Just push your new branch to the github repo.

**Comment by tydillon** [comment]
Done!

**Comment by MichaelGreco7** [comment]
Done...I was pushing to my forked repo
