### ISSUE TITLE
Confirm that you can pull API from github, run mongo(express) server, and node server on local machine AND send GET and POST requests to database

### ISSUE THREAD

**Issue by jrdukes** [jrscodeschool-5-2019/group-project-spring-2019#24]
Steps in terminal: 

1) `git checkout master` 
2) `git pull origin master`
3) run `mongoD` or `mongo` to start mongo server
4) create new tab in your terminal
5) navigate to `master` branch of project
6) `cd api`
7) `npm install`
8) `npm run dev` to start node server. 
*NOTE*: if you do not have `nodemon` installed globally, you'll get an error with `npm run dev`. Resolve this by installing nodemon globally with `npm i -g nodemon`
9) message should indicate `Server is listening on PORT 8000`
10) open another terminal tab and navigate to master branch of project, `cd api` and run `code .` to open VS Code or open `api` folder directly from VS Code.

Steps in Postman:
1) open Postman 
2) run a `GET` request with URL `http://localhost:8000/directory` to confirm you can communicate with database
3) run a `POST` request with URL `http://localhost:8000/directory`
4) choose `Body` `raw` `JSON(application/json`
5) In VS Code open the file `dummydata.json`
6) individually copy/paste the 5 objects in the `data` array in the `Body` and `Send` the `POST` request.

**Comment by AnnaCate** [comment]
NOTE: if you do not have nodemon installed globally, you'll get an error with `npm run dev`. Resolve this by installing nodemon globally with `npm i -g nodemon`

**Comment by AnnaCate** [comment]
👍🏼

**Comment by tydillon** [comment]
Got it!

**Comment by moquinad** [comment]
Done!

**Comment by MichaelGreco7** [comment]
Done.. well done Joe

**Comment by kevinleemoody** [comment]
Done
