### ISSUE TITLE
Confirm that everyone can get the project set up and running on their local machines

### ISSUE THREAD

**Issue by AnnaCate** [jrscodeschool-5-2019/group-project-spring-2019#3]
1. Clone
2. `npm install`
3. `npm start`
4. Open up browser and navigate to localhost:3000, where you should see 'Hello'

**Comment by AnnaCate** [comment]
Works for me 👍🏼

**Comment by tydillon** [comment]
Estoy bien! :)

**Comment by AnnaCate** [comment]
Everyone please make a comment when you have finished this task.

**Comment by VanSlam** [comment]
got it

**Comment by MichaelGreco7** [comment]
done

**Comment by jrdukes** [comment]
Completed
